name: Deploy Client Frontend

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
      - 'entities/**'
      - 'features/**'
      - 'pages/**'
      - 'plugins/**'
      - 'shared/**'
      - 'widgets/**'
      - 'error.vue'
      - 'nuxt.config.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'tailwind.config.js'

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies (for build)
        run: pnpm install --frozen-lockfile

      - name: Build App
        run: pnpm build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Deploy files to server
        run: |
          # Копируем .output
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/deploy_key" \
            ./.output/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PROJECT_DIR }}/.output/
            
          # Копируем package.json
          rsync -avz \
            -e "ssh -i ~/.ssh/deploy_key" \
            ./package.json \
            ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PROJECT_DIR }}/package.json
